from __future__ import annotations

import enum
import re
from collections.abc import Callable, Generator
from typing import Any, Generic, TypeVar, Union, List, overload

__version__: str

T = TypeVar("T")
U = TypeVar("U")

# parsy accepts str, bytes, or token lists
Stream = Union[str, bytes, List[Any]]

class Result(Generic[T]):
    status: bool
    index: int
    value: T
    furthest: int
    expected: frozenset[str]

    @staticmethod
    def success(index: int, value: T) -> Result[T]: ...
    @staticmethod
    def failure(index: int, expected: str | frozenset[str]) -> Result[Any]: ...
    def aggregate(self, other: Result[Any] | None) -> Result[T]: ...

class Parser(Generic[T]):
    def __init__(self, wrapped_fn: Callable[[Stream, int], Result[T]]) -> None: ...

    # low-level parse entrypoint used by @Parser decorator style
    def __call__(self, stream: Stream, index: int) -> Result[T]: ...

    # high-level entrypoints
    def parse(self, stream: Stream) -> T: ...
    def parse_partial(self, stream: Stream) -> tuple[T, Stream]: ...

    # core combinators
    def bind(self, bind_fn: Callable[[T], Parser[U]]) -> Parser[U]: ...
    def map(self, map_function: Callable[[T], U]) -> Parser[U]: ...
    def combine(self, combine_fn: Callable[..., U]) -> Parser[U]: ...
    def combine_dict(self, combine_fn: Callable[..., U]) -> Parser[U]: ...
    def concat(self) -> Parser[str]: ...

    # sequencing
    def then(self, other: Parser[U]) -> Parser[U]: ...
    def skip(self, other: Parser[Any]) -> Parser[T]: ...
    def result(self, value: U) -> Parser[U]: ...

    # repetition
    def many(self) -> Parser[list[T]]: ...
    def times(self, min: int, max: int | None = None) -> Parser[list[T]]: ...
    def at_most(self, n: int) -> Parser[list[T]]: ...
    def at_least(self, n: int) -> Parser[list[T]]: ...
    def optional(self, default: U | None = None) -> Parser[T | U]: ...
    def until(
        self,
        other: Parser[Any],
        min: int = 0,
        max: float = ...,
        consume_other: bool = False,
    ) -> Parser[list[T]]: ...
    def sep_by(
        self,
        sep: Parser[Any],
        *,
        min: int = 0,
        max: float = ...,
    ) -> Parser[list[T]]: ...

    # utilities
    def desc(self, description: str) -> Parser[T]: ...
    def mark(self) -> Parser[tuple[tuple[int, int], T, tuple[int, int]]]: ...
    def tag(self, name: str) -> Parser[tuple[str, T]]: ...
    def should_fail(self, description: str) -> Parser[None]: ...

    # operators
    @overload
    def __or__(self, other: Parser[T]) -> Parser[T]: ...
    @overload
    def __or__(self, other: Parser[U]) -> Parser[T | U]: ...
    def __or__(self, other: Parser[Any]) -> Parser[Any]: ...
    def __add__(self, other: Parser[U]) -> Parser[list[T | U]]: ...
    def __mul__(self, other: int | range) -> Parser[list[T]]: ...
    def __rshift__(self, other: Parser[U]) -> Parser[U]: ...
    def __lshift__(self, other: Parser[Any]) -> Parser[T]: ...

    # support decorator-style usage with @Parser in user code
    def __getattr__(self, name: str) -> Any: ...

# module-level constructors
def success(value: T) -> Parser[T]: ...
def fail(expected: str) -> Parser[Any]: ...
@overload
def alt(*parsers: Parser[T]) -> Parser[T]: ...
@overload
def alt(*parsers: Parser[Any]) -> Parser[Any]: ...
@overload
def seq(*parsers: Parser[T]) -> Parser[list[T]]: ...
@overload
def seq(**kw_parsers: Parser[T]) -> Parser[dict[str, T]]: ...
def generate(
    fn: Callable[..., Generator[Parser[Any], Any, T]],
) -> Parser[T]: ...
def string(expected_string: str, transform: Callable[[str], str] = ...) -> Parser[str]: ...
def regex(
    exp: str | bytes | re.Pattern[str],
    flags: int = 0,
    group: int | str | tuple[int | str, ...] = 0,
) -> Parser[str | tuple[str, ...]]: ...

# predefined parsers
index: Parser[int]
line_info: Parser[tuple[int, int]]
any_char: Parser[str]
whitespace: Parser[str]
letter: Parser[str]
digit: Parser[str]
decimal_digit: Parser[str]
eof: Parser[None]

def from_enum(
    enum_cls: type[enum.Enum],
    transform: Callable[[str], str] = ...,
) -> Parser[enum.Enum]: ...

class forward_declaration(Parser[T]):
    def become(self, other: Parser[T]) -> None: ...

# additional helpers commonly provided by parsy
def test_item(func: Callable[[Any], bool], description: str) -> Parser[Any]: ...
def test_char(func: Callable[[str], bool], description: str) -> Parser[str]: ...
def match_item(item: Any, description: str | None = None) -> Parser[Any]: ...
def string_from(*strings: str, transform: Callable[[str], str] = ...) -> Parser[str]: ...
def char_from(string: str | bytes) -> Parser[str | bytes]: ...
def peek(parser: Parser[T]) -> Parser[T]: ...
